app/models/customer.py
"""Customer modules to create table"""
from app.extensions import db
from datetime import datetime
import pytz


class Customer(db.Model):
    """ Customer model representing the 'customers' table in the database.

    Attributes:
        id (Integer): Primary key, unique identifier for each customer.
        customer_name (String): The name of the customer.
        customer_email (String): The email address of the customer.
        customer_phone (String): The phone number of the customer.
        frequentcy_pay (Integer): The number of times the customer has made
        payments.
        date (DateTime): The date when the customer record was created.

    Methods:
    __repr__(): Returns a string representation of the customer object.
    """
    __tablename__ = 'customers'
    id = db.Column(db.Integer, primary_key=True)
    customer_name = db.Column(db.String(200), nullable=False)
    customer_email = db.Column(db.String(200), nullable=False)
    customer_phone = db.Column(db.String(15))
    frequentcy_pay = db.Column(db.Integer, nullable=False)
    date = db.Column(db.DateTime, default=datetime.now(pytz.UTC))

    def __repr__(self):
        """ Returns a string representation of the customer object.

        Returns:

            str: A string that includes the customer's name and email.
        """
        return ('<Customer name %r Email %r>'
                % self.customer_name % self.customer_email)


def add_customer(sale):
    """ Adds a new customer or updates
    an existing customer's payment frequency.

    Parameters:
        sale: The sale object containing customer details.
    Returns:
        str: A message if failure
    """
    existing_customer = Customer.query.filter_by(
        customer_email=sale.customer_email).first()
    if existing_customer:
        existing_customer.frequentcy_pay += 1
    else:
        new_customer = Customer(customer_name=sale.customer_name,
                                customer_email=sale.customer_email,
                                customer_phone=sale.customer_phone,
                                frequentcy_pay=1)
        db.session.add(new_customer)
    try:
        db.session.commit()
    except:
        return 'There was an issue adding new customer'
    return 'Customer added/updated successfully'


def get_customer(search):
    """ Searches for customers in the database using a search pattern.

    Parameters:
        search: The search string to look for in customer records.

    Returns:
        list: A list of customer objects matching the search criteria.
    """
    search_pattern = f"%{search}"
    results = Customer.query.filter(
        (Customer.id.like(search_pattern))
        | (Customer.customer_name.like(search_pattern))
        | (Customer.customer_email.like(search_pattern))
        | (Customer.customer_phone.like(search_pattern))
        | (Customer.date.like(search_pattern))
    ).all()
    return results

app/customers/__init__.py
from flask import Blueprint


bp = Blueprint('customers', __name__)


from app.customers import routes

app/customers/routes.py
from flask import render_template, Response, jsonify
from flask import render_template, request
from flask_security import roles_accepted
from app.customers import bp
import io
import csv
import json
from app.import_export.export_customer import export_customer_json
from app.models.customer import Customer, get_customer


@bp.route('/', methods=['GET'])
@roles_accepted('admin', 'editor', 'supervisor')
def index():
    """ Display the list of customers.

    Methods:
        GET: Retrieve and display all customer records, ordered by date
          in descending order.

    Returns:
        Template: Render the customers/index.html template with customer data.
    """
    customers = Customer.query.order_by(Customer.date.desc()).all()
    return render_template('customers/index.html', customers=customers)


@bp.route('/search_customer/', methods=['GET', 'POST'])
@roles_accepted('admin', 'editor', 'supervisor')
def search_customer():
    """ Search for customers based on a search string.

    Methods:
        GET/POST: Retrieve and display customer records that match the
        search criteria.

    Returns:
        Template: Render the customers/search_customer.html
        template with search results.
    """
    search = request.args.get('search', '')
    customers = get_customer(search)
    return render_template('customers/search_customer.html',
                           customers=customers)


@bp.route('/download_customers')
@roles_accepted('admin')
def download_customers():
    """ Download customer data in the specified format (CSV or JSON).

    Methods:
        GET: Retrieve customer data and export it in the specified format.

    Returns:
        Response: A response containing the customer data file for download.
    """
    format = request.args.get('format')
    customers_dict = export_customer_json()

    if format == 'csv':
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(customers_dict[0].keys())
        for row in customers_dict:
            writer.writerow(row.values())
        output.seek(0)
        response = Response(output, mimetype='test/csv')
        response.headers['Content-Disposition'] = 'attachment; \
            filename=customers.csv'
    elif format == 'json':
        json_data = json.dumps(customers_dict, indent=4)
        response = Response(json_data, mimetype='application/json')
        response.headers['Content-Disposition'] = 'attachment; \
            filename=customers.json'
    else:
        return jsonify("Invalid format"), 400
    return response

app/templates/customers/index.html
{% extends 'base.html' %}

{% block head %}
<title>CRM</title>
{% endblock %}

{% block content %}
<div class="content">
    <div class='search'>
        <form action="{{ url_for('customers.search_customer', search='') }}" method="get">
            <input type='text' placeholder='Search' name='search' id='search'>
            <input type='submit' value="Search">
        </form>
    </div>
    <!--navigation through the records-->
    <div class="view">
        <h1 style="text-align: center;">Customers information</h1>
        {% if customers|length < 1 %}
        <h4  style="text-align: center;"> There are no customers yet !</h4>
        {% else %}
        <table>
            <tr>
                <th>Customer name</th>
                <th>Customer email</th>
                <th>Customer phone</th>
                <th>frequentcy pay</th>
                <th>date</th>
                <th>Id</th>
            </tr>
            {% for customer in customers %}
                <tr>
                    <td>{{ customer.customer_name }}</td>
                    <td>{{ customer.customer_email }}</td>
                    <td>{{ customer.customer_phone }}</td>
                    <td>{{ customer.frequentcy_pay }}</td>
                    <td>{{ customer.date.date() }}</td>
                    <td>{{ customer.id }}</td>
                </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>
    <div class="add">
        {% if current_user.has_role('admin')%}
        <div class="download-container">
            <button id="downloadBtn">Download</button>
            <div id="dropdown" class="dropdown-content">
                <a href="#" class="download-link" data-table="customers" data-format="json">JSON</a>
                <a href="#" class="download-link" data-table="customers" data-format="csv">CSV</a>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/customers/search_customer.html
{% extends 'base.html' %}

{% block head %}
<title>CRM</title>
{% endblock %}

{% block content %}
<div class="content">
    <div class='search'>
        <form action="{{ url_for('customers.search_customer', search='') }}" method="get">
            <input type='text' placeholder='Search' name='search' id='search'>
            <input type='submit' value="Search">
        </form>
    </div>
    <!--navigation through the records-->
    <div class="view">
        <h1 style="text-align: center;">Customers information</h1>
        {% if customers|length < 1 %}
        <h4  style="text-align: center;"> Not found !</h4>
        {% else %}
        <table>
            <tr>
                <th>Customer name</th>
                <th>Customer email</th>
                <th>Customer phone</th>
                <th>frequentcy pay</th>
                <th>date</th>
                <th>Id</th>
            </tr>
            {% for customer in customers %}
                <tr>
                    <td>{{ customer.customer_name }}</td>
                    <td>{{ customer.customer_email }}</td>
                    <td>{{ customer.customer_phone }}</td>
                    <td>{{ customer.frequentcy_pay }}</td>
                    <td>{{ customer.date.date() }}</td>
                    <td>{{ customer.id }}</td>
                </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/customers/view_customer.html
{% extends 'base.html' %}

{% block head %}
<title>CRM</title>
{% endblock %}

{% block content %}
<div class="content">
    <div class='search'>
        <form action="{{ url_for('search_customer', search='') }}" method="get">
            <input type='text' placeholder='Search' name='search' id='search'>
            <input type='submit' value="Search">
        </form>
    </div>
    <!--navigation through the records-->
    <div class="view">
        <h1 style="text-align: center;">Customers information</h1>
        {% if customers|length < 1 %}
        <h4  style="text-align: center;"> There are no customers yet !</h4>
        {% else %}
        <table>
            <tr>
                <th>Customer name</th>
                <th>Customer email</th>
                <th>Customer phone</th>
                <th>frequentcy pay</th>
                <th>date</th>
                <th>Id</th>
            </tr>
            {% for customer in customers %}
                <tr>
                    <td>{{ customer.customer_name }}</td>
                    <td>{{ customer.customer_email }}</td>
                    <td>{{ customer.customer_phone }}</td>
                    <td>{{ customer.frequentcy_pay }}</td>
                    <td>{{ customer.date.date() }}</td>
                    <td>{{ customer.id }}</td>
                </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}