app/models/user.py
"""user modules to create table"""
from app.extensions import db
from datetime import datetime
import pytz
from flask_security import UserMixin, RoleMixin
import uuid
import secrets
from sqlalchemy.orm import aliased


fs_uniquifier_value = str(uuid.uuid4())


def generate_unique_value():
    """Generate a secure, unique value for the fs_uniquifier.
    """
    return secrets.token_urlsafe(16)


class User(db.Model, UserMixin):
    """User model representing the 'user' table in the database.

    Attributes:
        id (Integer): Primary key, unique identifier for each user.
        user_name (String): The name of the user.
        user_email (String): The email address of the user.
        user_phone (String): The phone number of the user.
        password (String): The hashed password of the user.
        active (Boolean): Indicates if the user is active.
        roles (Relationship): Relationship to the Role model,
        representing the user's roles.
        date (DateTime): The date when the user record was created.
        fs_uniquifier (String): A unique identifier for Flask-Security.

    Methods:
        __repr__(): Returns a string representation of the user object.
    """
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    user_name = db.Column(db.String(200), nullable=False)
    user_email = db.Column(db.String(200), nullable=False)
    user_phone = db.Column(db.String(15))
    password = db.Column(db.String(128), nullable=False)
    active = db.Column(db.Boolean(), default=True)
    roles = db.relationship('Role', secondary='user_roles',
                            backref='roled')
    date = db.Column(db.DateTime, default=datetime.now(pytz.UTC))
    fs_uniquifier = db.Column(db.String(90), nullable=False,
                              unique=True,
                              default=generate_unique_value)

    def __repr__(self):
        """Returns a string representation of the user object.

        Returns:
            str: A string that includes the user's name.
        """
        return f'<User "{self.user_name}">'


class Role(db.Model, RoleMixin):
    """Role model representing the 'role' table in the database.

    Attributes:
        id (Integer): Primary key, unique identifier for each role.
        name (String): The name of the role.

    Methods:
        __repr__(): Returns a string representation of the role object.
    """
    __tablename__ = 'role'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True)

    def __repr__(self):
        """Returns a string representation of the role object.
        Returns:
            str: A string that includes the role's name.
        """
        return f'<User "{self.name}">'


class UserRoles(db.Model):
    """UserRoles model representing the 'user_roles'
    table in the database,
    mapping users to their roles.

    Attributes:
        id (Integer): Primary key, unique identifier for each mapping.
        user_id (Integer): Foreign key to the user ID.
        role_id (Integer): Foreign key to the role ID.
    """
    __tablename__ = 'user_roles'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id',
                                                  ondelete='CASCADE'))
    role_id = db.Column(db.Integer, db.ForeignKey('role.id',
                                                  ondelete='CASCADE'))


def create_roles():
    """Create default roles and add them to the database."""
    admin = Role(name='admin')
    editor = Role(name='editor')
    supervisor = Role(name='supervisor')
    try:
        db.session.add(admin)
        db.session.add(editor)
        db.session.add(supervisor)
        db.session.commit()
    except:
        return "fail to add roles to database"


def get_user(search):
    """Searches for users in the database using a search pattern.

    Parameters:
        search (str): The search string to look for in user records.

    Returns:
        list: A list of user objects matching the search criteria.
    """
    search_pattern = f"%{search}"
    RoleAlias = aliased(Role)
    results = User.query.filter(
        (User.id.like(search_pattern))
        | (User.user_name.like(search_pattern))
        | (User.user_email.like(search_pattern))
        | (User.user_phone.like(search_pattern))
        | (RoleAlias.name.like(search_pattern))
        | (User.date.like(search_pattern))
    ).all()
    return results

app/users/__init__.py
from flask import Blueprint


bp = Blueprint('users', __name__)


from app.users import routes

app/users/routes.py
from flask import render_template
from flask import render_template, request, redirect, url_for
from flask_login import login_user, logout_user, login_required
from flask_security import roles_accepted
from app.users import bp
from app.extensions import db, bcrypt
from app.models.user import User, Role, get_user


@bp.route('/', methods=['GET'])
@roles_accepted('admin', 'supervisor')
def index():
    """ Display the list of users.

    Methods:
        GET: Retrieve and display all user records, ordered by user name.

    Returns:
        Template: Render the users/index.html template with user data.
    """
    users = User.query.order_by(User.user_name).all()
    return render_template('users/index.html', users=users)


@bp.route('/search_user/', methods=['GET', 'POST'])
@roles_accepted('admin', 'supervisor')
def search_user():
    """ Search for users based on a search string.

    Methods:
        GET/POST: Retrieve and display user records that match the search
        criteria.

    Returns:
        Template: Render the users/search_user.html template with
        search results.
    """
    search = request.args.get('search', '')
    users = get_user(search)
    return render_template('users/search_user.html', users=users)


@bp.route('/add_user/', methods=['POST', 'GET'])
@roles_accepted('admin')
def add_user():
    """ Add a new user.

    Methods:
        GET: Render the add user template.
        POST: Add a new user to the database.

    Returns:
        Template or redirect: Render the add user template or redirect
        to the users index.
    """
    if request.method == 'POST':
        user_name = request.form['user']
        user_email = request.form['user_email']
        user_phone = request.form['user_phone']
        password = request.form['user_password']
        user_role = request.form['privilege']

        hashed_password = bcrypt.generate_password_hash(password
                                                        ).decode('utf-8')
        role = Role.query.filter_by(name=user_role).first()
        new_user = User(user_name=user_name, user_email=user_email,
                        user_phone=user_phone, password=hashed_password)
        new_user.roles.append(role)
        try:
            db.session.add(new_user)
            db.session.commit()
            return redirect(url_for("users.index"))
        except:
            return 'There was an error adding user'
    else:
        return render_template('users/add_user.html')


@bp.route('/info_user/<int:id>', methods=['GET'])
@roles_accepted('admin', 'supervisor')
def info_user(id):
    """ Display information about a single user.

    Methods:
        GET: Retrieve and display information about a specific user.
    Returns:
        Template: Render the users/info_user.html template with user data.
    """
    user = User.query.get_or_404(id)
    return render_template('users/info_user.html', user=user)


@bp.route('/delete_user/<int:id>')
@roles_accepted('admin')
def delete_user(id):
    """ Delete a single user.

    Methods:
        GET: Delete a specific user from the database.

    Returns:
        Redirect: Redirect to the users index after deletion.
    """
    user_to_delete = User.query.get_or_404(id)

    try:
        db.session.delete(user_to_delete)
        db.session.commit()
        return redirect(url_for("users.index"))
    except:
        return 'delete error'


@bp.route('/update_user/<int:id>', methods=['GET', 'POST'])
@roles_accepted('admin')
def update_user(id):
    """ Update information about a single user.

    Methods:
        GET: Render the update user template with the current user data.
        POST: Update the user information in the database.

    Returns:
        Template or redirect: Render the update user template or redirect
        to the users index.
    """
    user = User.query.get_or_404(id)
    if request.method == 'POST':
        user.user_name = request.form['user']
        user.user_email = request.form['user_email']
        user.user_phone = request.form['user_phone']
        user.password = request.form['user_password']
        user.type = request.form['privilege']

        try:
            db.session.commit()
            return redirect(url_for("users.index"))
        except:
            return 'db update error'

    else:
        return render_template('users/update_user.html', user=user)

app/templates/users/add_user.html
{% extends 'base.html' %}

{% block head %}
<title>CRM</title>
{% endblock %}

{% block content %}
<div class="content">
    <div class="add_update">
        <div class="form-box">
            <h1>Add new User</h1>
            <form action="/users/add_user" method="post">
                <div class="input-group">
                    <label>User name</label>
                    <div class="input-field">
                        <input type="text" name="user" id="user" required>
                    </div>
                </div>
                <div class="input-group">
                    <label>User email</label>
                    <div class="input-field">
                        <input type="email" name="user_email" id="user_email"  required>
                    </div>
                </div>
                <div class="input-group">
                    <label>User phone</label>
                    <div class="input-field">
                        <input type="tel" name="user_phone" id="user_phone">
                    </div>
                </div>
                <div class="input-group">
                    <label>Password</label>
                    <div class="input-field">
                        <input type="password" name="user_password" id="user_password" required>
                    </div>
                </div>
                <div class="input-group">
                    <label for="userPrivilege">Select User Privilege</label>
                    <div class="input-field">
                        <select id="privilege" name="privilege">
                            <option value="admin">Admin</option>
                            <option value="editor">Editor</option>
                            <option value="supervisor">Supervisor</option>
                        </select>
                    </div>
                </div>
                <div class="input-filed">
                    <input type="submit" value="Add" name="add" id="add">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/users/index.html
{% extends 'base.html' %}

{% block content %}
<div class="content">
    <div class='search'>
        <form action="{{ url_for('users.search_user', search='') }}" method="get">
            <input type='text' placeholder='Search' name='search' id='search'>
            <input type='submit' value="Search">
        </form>
    </div>
    <!--navigation through the records-->
    <div class="view">
        <h1 style="text-align: center;">Users information</h1>
        {% if users|length < 1 %}
        <h4  style="text-align: center;"> There are no users, create one below!</h4>
        {% else %}
        <table>
            <tr>
                <th>User name</th>
                <th>User email</th>
                <th>User phone</th>
                <th>Privilage</th>
                <th>date</th>
                <th>Id</th>
            </tr>
            {% for user in users %}
                <tr>
                    <td>{{ user.user_name }}</td>
                    <td>{{ user.user_email }}</td>
                    <td>{{ user.user_phone }}</td>
                    <td>{{ user.roles[0].name }}</td>
                    <td>{{ user.date.date() }}</td>
                    <td><a href="/users/info_user/{{ user.id }}">{{ user.id }}</a></td>
                </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>
    <div class="add">
        {% if current_user.has_role('admin') or current_user.has_role('editor')%}
        <a href="/users/add_user">Add user</a>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/users/info_user.html
{% extends 'base.html' %}

{% block head %}
<title>CRM</title>
{% endblock %}

{% block content %}
<div class="content">
    <div class="info">
        <div class="table_box">
            <table>
                <tr>
                    <th>User</th>
                    <td>{{ user.user_name }}</td>
                </tr>
                <tr>
                    <th>User email</th>
                    <td>{{ user.user_email }}</td>
                </tr>
                <tr>
                    <th>User phone</th>
                    <td>{{ user.user_phone }}</td>
                </tr>
                <tr>
                    <th>Privilage</th>
                    <td>{{ user.roles[0].name }}</td>
                </tr>
                <tr>
                    <th>Date</th>
                    <td>{{ user.date.date() }}</td>
                </tr>
            </table>
        </div>
        <div class="edit">
            {% if current_user.has_role('admin') or current_user.has_role('editor')%}
            <a href="/users/update_user/{{user.id}}" id="update">Update</a>
            <br/>
            <a href="{{ url_for('users.delete_user', id=user.id) }}" onclick="return confirm('are you sure you want delete this record?!')" id="delete">Delete</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/users/login.html
{% extends 'base.html' %}

{% block head %}
<title>CRM</title>
{% endblock %}

{% block content %}
<div class="login">
    <div class="form-box">
        <h1>Login</h1>
            <form action="" method="post">
                <div class="input-group">
                    <div class="input-filed">
                        <input type="email" name="email" id="email" placeholder="Email" required>
                    </div>
                    <div class="input-filed">
                        <input type="password" name="password" id="password" placeholder="Password" required>
                    </div>
                        <div class="input-filed">
                            <input type="submit" name="Login" value="Login">
                        </div>
                    </div>
                </form>
            </div>
        </div> 
{% endblock %}

app/templates/users/search_user.html
{% extends 'base.html' %}

{% block head %}
<title>CRM</title>
{% endblock %}

{% block content %}
<div class="content">
    <div class='search'>
        <form action="{{ url_for('users.search_user', search='') }}" method="get">
            <input type='text' placeholder='Search' name='search' id='search'>
            <input type='submit' value="Search">
        </form>
    </div>
    <!--navigation through the records-->
    <div class="view">
        <h1 style="text-align: center;">Users information</h1>
        {% if users|length < 1 %}
        <h4  style="text-align: center;"> Not found </h4>
        {% else %}
        <table>
            <tr>
                <th>User name</th>
                <th>User email</th>
                <th>User phone</th>
                <th>Privilage</th>
                <th>date</th>
                <th>Id</th>
            </tr>
            {% for user in users %}
                <tr>
                    <td>{{ user.user_name }}</td>
                    <td>{{ user.user_email }}</td>
                    <td>{{ user.user_phone }}</td>
                    <td>{{ user.roles[0].name }}</td>
                    <td>{{ user.date.date() }}</td>
                    <td><a href="/users/info_user/{{ user.id }}">{{ user.id }}</a></td>
                </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/users/update_user.html
{% extends 'base.html' %}

{% block head %}
<title>CRM</title>
{% endblock %}

{% block content %}
<div class="content">
    <div class="add_update">
        <div class="form-box">
            <h1  style="text-align: center;">Update user information</h1>
            <form action="/users/update_user/{{user.id}}" method="post">
                <div class="input-group">
                    <label>User name</label>
                    <div class="input-field">
                        <input type="text" name="user" id="user" value="{{ user.user_name }}" required>
                    </div>
                </div>
                <div class="input-group">
                    <label>User email</label>
                    <div class="input-field">
                        <input type="email" name="user_email" id="user_email" value="{{ user.user_email }}" required>
                    </div>
                </div>
                <div class="input-group">
                    <label>User phone</label>
                    <div class="input-field">
                        <input type="tel" name="user_phone" id="user_phone" value="{{ user.user_phone }}">
                    </div>
                </div>
                <div class="input-group">
                    <label>Password</label>
                    <div class="input-field">
                        <input type="password" name="user_password" id="user_password"required>
                    </div>
                </div>
                <div class="input-group">
                    <label for="userPrivilege">User Privilege</label>
                    <div class="input-field">
                        <select id="privilege" name="privilege">
                            <option value="admin">Admin</option>
                            <option value="editor">Editor</option>
                            <option value="supervisor">Supervisor</option>
                        </select>
                    </div>
                </div>
                <div class="input-field">
                    {% if current_user.has_role('admin') or current_user.has_role('editor')%}
                    <input type="submit" value="Update" name="update" id="update">
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/users/view_user.html
{% extends 'base.html' %}

{% block head %}
<title>CRM</title>
{% endblock %}

{% block content %}
<div class="content">
    <div class='search'>
        <form action="{{ url_for('search_user', search='') }}" method="get">
            <input type='text' placeholder='Search' name='search' id='search'>
            <input type='submit' value="Search">
        </form>
    </div>
    <!--navigation through the records-->
    <div class="view">
        <h1 style="text-align: center;">Users information</h1>
        {% if users|length < 1 %}
        <h4  style="text-align: center;"> There are no users, create one below!</h4>
        {% else %}
        <table>
            <tr>
                <th>User name</th>
                <th>User email</th>
                <th>User phone</th>
                <th>Privilage</th>
                <th>date</th>
                <th>Id</th>
            </tr>
            {% for user in users %}
                <tr>
                    <td>{{ user.user_name }}</td>
                    <td>{{ user.user_email }}</td>
                    <td>{{ user.user_phone }}</td>
                    <td>{{ user.roles[0].name }}</td>
                    <td>{{ user.date.date() }}</td>
                    <td><a href="/info_user/{{ user.id }}">{{ user.id }}</a></td>
                </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>
    <div class="add">
        {% if current_user.has_role('admin') or current_user.has_role('editor')%}
        <a href="/add_user">Add user</a>
        {% endif %}
    </div>
</div>
{% endblock %}