app/models/product.py
"""Product modules to create table"""
from app.extensions import db
from datetime import datetime
import pytz


class Product(db.Model):
    """Product model representing the 'products' table in the database.

    Attributes:
        id (Integer): Primary key, unique identifier for each product.
        product_name (String): The name of the product.
        price (Integer): The price of the product.
        product_quantity (Integer): The quantity of the product available.
        date (DateTime): The date when the product record was created.

    Methods: __repr__():
        Returns a string representation of the product object.
    """
    __tablename__ = 'products'
    id = db.Column(db.Integer, primary_key=True)
    product_name = db.Column(db.String(200), nullable=False)
    price = db.Column(db.Integer, nullable=False)
    product_quantity = db.Column(db.Integer, nullable=False)
    date = db.Column(db.DateTime, default=datetime.now(pytz.UTC))

    def __repr__(self):
        """Returns a string representation of the product object.

        Returns:
            str: A string that includes the product's name and price.
        """
        return ('<Product name %r Price %r>'
                % self.product_name % self.price)


def get_product(search):
    """Searches for products in the database using a search pattern.

    Parameters:
        search: The search string to look for in product records.

    Returns:
        list: A list of product objects matching the search criteria.
    """
    search_pattern = f"%{search}"
    results = Product.query.filter(
        (Product.id.like(search_pattern))
        | (Product.product_name.like(search_pattern))
        | (Product.price.like(search_pattern))
    ).all()
    return results

app/products/__init__.py
from flask import Blueprint


bp = Blueprint('products', __name__)


from app.products import routes

app/products/routes.py
from flask import render_template
from flask import render_template, url_for, request, redirect, Response
from flask_security import roles_accepted
from app.products import bp
from app.extensions import db
from flask import jsonify
import io
import csv
import json
import os
from werkzeug.utils import secure_filename
from sqlalchemy import inspect


from app.models.product import Product, get_product
from app.import_export.export_product import export_product_json
from app.import_export.import_sale import allowed_file
from app.import_export.import_product import (parse_products_csv_file,
                                              parse_products_json_file)


@bp.route('/', methods=['GET'])
@roles_accepted('admin', 'editor', 'supervisor')
def index():
    """ Display the list of products.

    Methods:
        GET: Retrieve and display all product records, ordered by
        product name.

    Returns: Template: Render the products/index.html template with
    product data.
    """
    products = Product.query.order_by(Product.product_name).all()
    return render_template('products/index.html', products=products)


@bp.route('/search_product/', methods=['GET', 'POST'])
@roles_accepted('admin', 'editor', 'supervisor')
def search_product():
    """ Search for products based on a search string.

    Methods:
        GET/POST: Retrieve and display product records that match the
        search criteria.

    Returns:
        Template: Render the products/search_product.html template
        with search results.
    """
    search = request.args.get('search', '')
    products = get_product(search)
    return render_template('products/search_product.html', products=products)


@bp.route('/add_product/', methods=['POST', 'GET'])
@roles_accepted('admin', 'editor')
def add_product():
    """ Add a new product.

    Methods:
        GET: Render the add product template.
        POST: Add a new product to the database.

    Returns:
        Template or redirect: Render the add product template or redirect
          to the products index.
    """
    if request.method == 'POST':
        product_name = request.form['product']
        price = request.form['price']
        product_quantity = request.form['quantity']
        existing_product = Product.query.filter_by(product_name=product_name
                                                   ).first()
        if existing_product:
            return "This product is already in the store, try update it!"
        new_product = Product(product_name=product_name, price=price,
                              product_quantity=product_quantity)
        try:
            db.session.add(new_product)
            db.session.commit()
            return redirect(url_for('products.index'))
        except:
            return 'There was an error adding your product'
    else:
        return render_template('products/add_product.html')


@bp.route('/info_product/<int:id>', methods=['GET'])
@roles_accepted('admin', 'editor', 'supervisor')
def info_product(id):
    """ Display information about a single product.

    Methods:
        GET: Retrieve and display information about a specific product.

    Returns:
        Template: Render the products/info_product.html template with
        product data.
    """
    product = Product.query.get_or_404(id)
    return render_template('products/info_product.html', product=product)


@bp.route('/delete_product/<int:id>')
@roles_accepted('admin', 'editor')
def delete_product(id):
    """ Delete a single product.

    Methods:
        GET: Delete a specific product from the database.
    Returns: Redirect: Redirect to the products index after deletion.
    """
    product_to_delete = Product.query.get_or_404(id)

    try:
        db.session.delete(product_to_delete)
        db.session.commit()
        return redirect(url_for('products.index'))
    except:
        return 'delete error'


@bp.route('/update_product/<int:id>', methods=['GET', 'POST'])
@roles_accepted('admin', 'editor')
def update_product(id):
    """ Update information about a single product.

    Methods:
        GET: Render the update product template with the current product
          data. POST: Update the product information in the database.

    Returns:
        Template or redirect: Render the update product template or
        redirect to the products index.
    """
    product = Product.query.get_or_404(id)
    if request.method == 'POST':
        product.product_name = request.form['product']
        product.price = request.form['price']
        product.product_quantity = request.form['quantity']

        try:
            db.session.commit()
            return redirect(url_for('products.index'))
        except:
            return 'db update error'

    else:
        return render_template('products/update_product.html', product=product)


@bp.route('/download_products')
@roles_accepted('admin', 'editor')
def download_products():
    """ Download product data in the specified format (CSV or JSON).

    Methods:
        GET: Retrieve product data and export it in the specified format.

    Returns:
        Response: A response containing the product data file for
        download.
    """
    format = request.args.get('format')
    products_dict = export_product_json()

    if format == 'csv':
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(products_dict[0].keys())
        for row in products_dict:
            writer.writerow(row.values())
        output.seek(0)
        response = Response(output, mimetype='test/csv')
        response.headers['Content-Disposition'] = 'attachment; \
            filename=products.csv'
    elif format == 'json':
        json_data = json.dumps(products_dict, indent=4)
        response = Response(json_data, mimetype='application/json')
        response.headers['Content-Disposition'] = 'attachment; \
            filename=products.json'
    else:
        return "Invalid format", 400
    return response


@bp.route('/upload_product', methods=['POST', 'GET'])
@roles_accepted('admin', 'editor')
def upload_products():
    """ Upload product data from a file (CSV or JSON).

    Methods:
        GET: Render the upload product template.
        POST: Handle the file upload and import product data.

    Returns:
        Template or JSON response: Render the upload product template
        or return a JSON response indicating the result of the
        operation.
    """
    if request.method == 'POST':
        if 'file' not in request.files:
            return jsonify({"error": "No file part"}), 400

        uploaded_file = request.files['file']
        if uploaded_file == '':
            return jsonify({"error": "No selected file"}), 400

        if uploaded_file and allowed_file(uploaded_file.filename):
            filename = secure_filename(uploaded_file.filename)
            extention = filename.rsplit('.', 1)[1].lower()
            file_path = os.path.join('uploads/', filename)
            uploaded_file.save(file_path)
            filename.rsplit('.', 1)[1].lower()
            if extention == 'json':
                msg = parse_products_json_file(file_path)
                return msg
            elif extention == 'csv':
                inspector = inspect(db.engine)
                msg = parse_products_csv_file(inspector, file_path)
                return msg
            else:
                pass
            return redirect(url_for('products.index'))
        else:
            return jsonify({"error": "File not allowed"}), 400
    return render_template('upload_product')

app/templates/products/add_product.html
{% extends 'base.html' %}

{% block head %}
<title>CRM</title>
{% endblock %}

{% block content %}
<div class="content">
    <div class="add_update">
        <div class="form-box">
            <h1>Add new Product</h1>
            <form action="/products/add_product" method="post">
                <div class="input-group">
                    <label>Product</label>
                    <div class="input-field">
                        <input type="text" name="product" id="product" required>
                    </div>
                </div>
                <div class="input-group">
                    <label>Price</label>
                    <div class="input-field">
                        <input type="text" name="price" id="price" required>
                    </div>
                </div>
                <div class="input-group">
                    <label>Quantity</label>
                    <div class="input-field">
                        <input type="number" name="quantity" id="quantity" required>
                    </div>
                </div>
                <div class="input-filed">
                    <input type="submit" value="Add" name="add" id="add">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/products/index.html
{% extends 'base.html' %}

{% block head %}
<title>CRM</title>
{% endblock %}

{% block content %}
<div class="content">
    <div class='search'>
        <form action="{{ url_for('products.search_product', search='') }}" method="get">
            <input type='text' placeholder='Search' name='search' id='search'>
            <input type='submit' value="Search">
        </form>
    </div>
    <!--navigation through the records-->
    <div class="view">
        <h1 style="text-align: center;">Products information</h1>
        {% if products|length < 1 %}
        <h4  style="text-align: center;"> There are no product on the store, create one below!</h4>
        {% else %}
        <table>
            <tr>
                <th>Product</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Date</th>
                <th>Id</th>
            </tr>
            {% for product in products %}
                <tr>
                    <td>{{ product.product_name }}</td>
                    <td>{{ product.price }}</td>
                    <td>{{ product.product_quantity }}</td>
                    <td>{{ product.date.date() }}</td>
                    <td><a href="/products/info_product/{{ product.id }}">{{ product.id }}</a></td>
                </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>
    <div class="add">
        {% if current_user.has_role('admin') or current_user.has_role('editor')%}
        <a href="/products/add_product">Add product</a>
        <div class="download-container">
            <button id="downloadBtn">Download</button>
            <div id="dropdown" class="dropdown-content">
                <a href="#" class="download-link" data-table="products" data-format="json">JSON</a>
                <a href="#" class="download-link" data-table="products" data-format="csv">CSV</a>
            </div>
        </div>
        <div class="upload-container">
            <button id="openModalBtn">Upload</button>
            <div id="uploadModal" class="modal">
                <div class="modal-content">
                    <span class="close">&times;</span>
                    <form id="uploadForm">
                        <input type="file" id="fileInput" name="file">
                        <button type="submit">Upload</button>
                    </form>
                </div>
            </div> 
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/products/info_product.html
{% extends 'base.html' %}

{% block head %}
<title>CRM</title>
{% endblock %}

{% block content %}
<div class="content">
    <div class="info">
        <div class="table_box">
            <table>
                <tr>
                    <th>Product</th>
                    <td>{{ product.product_name }}</td>
                </tr>
                <tr>
                    <th>Price</th>
                    <td>{{ product.price }}</td>
                </tr>
                <tr>
                    <th>Quantity</th>
                    <td>{{ product.product_quantity }}</td>
                </tr>
                <tr>
                    <th>Date</th>
                    <td>{{ product.date.date() }}</td>
                </tr>
            </table>
        </div>
        <div>
            {% if current_user.has_role('admin') or current_user.has_role('editor')%}
            <a href="/products/update_product/{{product.id}}" id="update">Update</a>
            <br>
            <a href="{{ url_for('products.delete_product', id=product.id) }}" onclick="return confirm('are you sure you want delete this record?!')" id="delete">Delete</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/products/search_product.html
{% extends 'base.html' %}

{% block head %}
<title>CRM</title>
{% endblock %}

{% block content %}
<div class="content">
    <div class='search'>
        <form action="{{ url_for('products.search_product', search='') }}" method="get">
            <input type='text' placeholder='Search' name='search' id='search'>
            <input type='submit' value="Search">
        </form>
    </div>
    <!--navigation through the records-->
    <div class="view">
        <h1 style="text-align: center;">Products information</h1>
        {% if products|length < 1 %}
        <h4  style="text-align: center;"> There are no product on the store, create one below!</h4>
        {% else %}
        <table>
            <tr>
                <th>Product</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Date</th>
                <th>Id</th>
            </tr>
            {% for product in products %}
                <tr>
                    <td>{{ product.product_name }}</td>
                    <td>{{ product.price }}</td>
                    <td>{{ product.product_quantity }}</td>
                    <td>{{ product.date.date() }}</td>
                    <td><a href="/products/info_product/{{ product.id }}">{{ product.id }}</a></td>
                </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/products/update_product.html
{% extends 'base.html' %}

{% block head %}
<title>CRM</title>
{% endblock %}

{% block content %}
<div class="content">
    <div class="add_update">
        <div class="form-box">
            <h1  style="text-align: center;">Update product information</h1>
            <form action="/products/update_product/{{product.id}}" method="post">
                <div class="input-group">
                    <label>Product</label>
                    <div class="input-field">
                        <input type="text" name="product" id="product" value="{{ product.product_name }}" required>
                    </div>
                </div>
                <div class="input-group">
                    <label>Price</label>
                    <div class="input-field">
                        <input type="text" name="price" id="price" value="{{ product.price }}" required>
                    </div>
                </div>
                <div class="input-group">
                    <label>Quantity</label>
                    <div class="input-field">
                        <input type="number" name="quantity" id="quantity" value="{{ product.product_quantity }}" required>
                    </div>
                </div>
                <div class="input-field">
                    {% if current_user.has_role('admin') or current_user.has_role('editor')%}
                    <input type="submit" value="Update" name="update" id="update">
                    {% endif %}
                </div> 
            </form>
        </div>
    </div>
</div>
{% endblock %}