app/models/sale.py
"""sale modules to create table"""
from app.extensions import db
from datetime import datetime
import pytz


class Sale(db.Model):
    """Sale model representing the 'sales' table in the database.

    Attributes:
        id (Integer): Primary key, unique identifier for each sale.
        product_name (String): The name of the product sold.
        product_quantity (Integer): The quantity of the product sold.
        customer_name (String): The name of the customer.
        customer_email (String): The email address of the customer.
        customer_phone (String): The phone number of the customer.
        user_name (String): The name of the user who processed the sale.
        date (DateTime): The date when the sale record was created.

    Methods: __repr__():
    Returns a string representation of the sale object.
    """
    __tablename__ = 'sales'
    id = db.Column(db.Integer, primary_key=True)
    product_name = db.Column(db.String(200), nullable=False)
    product_quantity = db.Column(db.Integer, nullable=False)
    customer_name = db.Column(db.String(200), nullable=False)
    customer_email = db.Column(db.String(200), nullable=False)
    customer_phone = db.Column(db.String(15))
    user_name = db.Column(db.String(200), nullable=False)
    date = db.Column(db.DateTime, default=datetime.now(pytz.UTC))

    def __repr__(self):
        """Returns a string representation of the sale object.

        Returns:
            str: A string that includes the sale's ID and product name.
        """
        return ('<sale id %r product name %r>'
                % self.id % self.product_name)


def get_sales(search):
    """Searches for sales in the database using a search pattern.

    Parameters:
        search: The search string to look for in sale records.

    Returns:
        list: A list of sale objects matching the search criteria.
    """
    search_pattern = f"%{search}"
    results = Sale.query.filter(
        (Sale.id.like(search_pattern))
        | (Sale.product_name.like(search_pattern))
        | (Sale.customer_name.like(search_pattern))
        | (Sale.customer_email.like(search_pattern))
        | (Sale.user_name.like(search_pattern))
        | (Sale.date.like(search_pattern))
    ).all()
    return results

app/sales/__init__.py
from flask import Blueprint


bp = Blueprint('sales', __name__)


from app.sales import routes

app/sales/routes.py
from flask import (render_template, request, redirect, url_for,
                   Response, get_flashed_messages)
from flask_security import roles_accepted
from app.sales import bp
from app.extensions import db
import csv
import io
import json
import os
from werkzeug.utils import secure_filename
from sqlalchemy import inspect
from flask import jsonify
from app.models.sale import Sale, get_sales
from app.import_export.export_sale import export_sale_json
from app.import_export.import_sale import (allowed_file, parse_sales_json_file,
                                           parse_sales_csv_file)
from app.models.product import Product
from app.models.customer import add_customer


@bp.route('/', methods=['GET'])
@roles_accepted('admin', 'editor', 'supervisor')
def index():
    """ Display the list of sales.

    Methods:
        GET: Retrieve and display all sale records, ordered by date in
        descending order.

    Returns: Template: Render the sales/index.html template with sale
    data.
    """
    sales = Sale.query.order_by(Sale.date.desc()).all()
    return render_template('sales/index.html', sales=sales)


@bp.route('/search_sale/', methods=['GET', 'POST'])
@roles_accepted('admin', 'editor', 'supervisor')
def search_sale():
    """ Search for sales based on a search string.

    Methods:
        GET/POST: Retrieve and display sale records that match the
        search criteria.

    Returns: Template: Render the sales/search_sale.html template
    with search results.
    """
    search = request.args.get('search', '')
    sales = get_sales(search)
    return render_template('sales/search_sale.html', sales=sales)


@bp.route('/add_sale/', methods=['POST', 'GET'])
@roles_accepted('admin', 'editor')
def add_sale():
    """ Add a new sale.

    Methods:
        GET: Render the add sale template.
        POST: Add a new sale to the database.

    Returns:
        Template or redirect: Render the add sale template or
        redirect to the sales index.
    """
    if request.method == 'POST':
        error = ""
        product = request.form['product']
        quantity = request.form['quantity']
        customer = request.form['customer']
        customer_email = request.form['customer_email']
        customer_phone = request.form['customer_phone']
        user = request.form['user']
        prod = Product.query.filter_by(product_name=product).first()
        if prod:
            if prod.product_quantity < int(quantity):
                error = 'Not enough quantity'
            else:
                prod.product_quantity -= int(quantity)
                try:
                    db.session.commit()
                except:
                    return 'There was an issue updating product quantity'
        else:
            error = 'Product not found'
        if error:
            return render_template('add_sale.html', product=product,
                                   quantity=quantity, customer=customer,
                                   customer_email=customer_email,
                                   customer_phone=customer_phone,
                                   user=user, error=error)
        new_sale = Sale(product_name=product, product_quantity=quantity,
                        customer_name=customer, customer_email=customer_email,
                        customer_phone=customer_phone, user_name=user)
        try:
            db.session.add(new_sale)
            db.session.commit()
            add_customer(new_sale)
            return redirect(url_for('sales.index'))
        except:
            return 'There was an issue adding your sale information'
    else:
        return render_template('sales/add_sale.html')


@bp.route('/info_sale/<int:id>', methods=['GET'])
@roles_accepted('admin', 'editor', 'supervisor')
def info_sale(id):
    """ Display information about a single sale.

    Methods:
        GET: Retrieve and display information about a specific sale.

    Returns:
        Template: Render the sales/info_sale.html template with sale data.
    """
    sale = Sale.query.get_or_404(id)
    return render_template('sales/info_sale.html', sale=sale)


@bp.route('/delete_sale/<int:id>')
@roles_accepted('admin', 'editor')
def delete_sale(id):
    """ Delete a single sale.

    Methods:
        GET: Delete a specific sale from the database.

    Returns:
        Redirect: Redirect to the sales index after deletion.
    """
    sale_to_delete = Sale.query.get_or_404(id)

    try:
        db.session.delete(sale_to_delete)
        db.session.commit()
        return redirect(url_for('sales.index'))
    except:
        return 'delete error'


@bp.route('/update_sale/<int:id>', methods=['GET', 'POST'])
@roles_accepted('admin', 'editor')
def update_sale(id):
    """ Update information about a single sale.

    Methods:
        GET: Render the update sale template with the current sale data.
        POST: Update the sale information in the database.

    Returns:
        Template or redirect: Render the update sale template or
        redirect to the sales index.
    """
    sale = Sale.query.get_or_404(id)
    if request.method == 'POST':
        product = request.form['product']
        quantity = request.form['quantity']
        sale.customer_name = request.form['customer']
        sale.user_name = request.form['user']
        prod = Product.query.filter_by(product_name=product).first()
        if prod:
            if prod.product_quantity < int(quantity):
                error = 'Not enough quantity'
            else:
                prod.product_quantity += sale.product_quantity
                prod.product_quantity -= int(quantity)
                sale.product_name = product
                sale.product_quantity = quantity
                try:
                    db.session.commit()
                    return redirect(url_for('sales.index'))
                except:
                    return 'db update error'
        else:
            error = 'Product not found'
        return render_template('sales/update_sale.html', sale=sale,
                               error=error)
    else:
        return render_template('sales/update_sale.html', sale=sale)


@bp.route('/download_sales')
@roles_accepted('admin')
def download_sales():
    """ Download sale data in the specified format (CSV or JSON).

    Methods:
        GET: Retrieve sale data and export it in the specified format.

    Returns: Response: A response containing the sale data file for
    download.
    """
    format = request.args.get('format')
    sales_dict = export_sale_json()

    if format == 'csv':
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(sales_dict[0].keys())
        for row in sales_dict:
            writer.writerow(row.values())
        output.seek(0)
        response = Response(output, mimetype='test/csv')
        response.headers['Content-Disposition'] = 'attachment; \
            filename=sales.csv'
    elif format == 'json':
        json_data = json.dumps(sales_dict, indent=4)
        response = Response(json_data, mimetype='application/json')
        response.headers['Content-Disposition'] = 'attachment; \
            filename=sales.json'
    else:
        return "Invalid format", 400
    return response


@bp.route('/upload_sales', methods=['POST', 'GET'])
@roles_accepted('admin', 'editor')
def upload_sales():
    """ Upload sale data from a file (CSV or JSON).

    Methods: GET: Render the upload sale template.
    POST: Handle the file upload and import sale data.

    Returns: Template or JSON response: Render the upload sale template
    or return a JSON response indicating the result of the operation.
    """
    if request.method == 'POST':
        if 'file' not in request.files:
            return jsonify({"error": "No file part"}), 400

        uploaded_file = request.files['file']
        if uploaded_file == '':
            return jsonify({"error": "No selected file"}), 400

        if uploaded_file and allowed_file(uploaded_file.filename):
            filename = secure_filename(uploaded_file.filename)
            extention = filename.rsplit('.', 1)[1].lower()
            file_path = os.path.join('uploads/', filename)
            uploaded_file.save(file_path)
            filename.rsplit('.', 1)[1].lower()
            if extention == 'json':
                msg = parse_sales_json_file(file_path)
                return msg
            elif extention == 'csv':
                inspector = inspect(db.engine)
                return parse_sales_csv_file(inspector, file_path)
            else:
                pass
            return redirect(url_for('sales.index'))
        else:
            return jsonify({"error": "File not allowed"}), 400
    return render_template('upload_sales')

app/templates/sales/add_sale.html
{% extends 'base.html' %}

{% block head %}
<title>CRM</title>
{% endblock %}

<div class="content">
{% block content %}
    <div class="add_update">
        <div class="form-box">
            <h1>Add new Sale</h1>
            <form action="/sales/add_sale" method="post">
                <div class="input-group">
                    <label>Product</label>
                    <div class="input-field {% if error == 'Product not found' %}error-field{% endif %}">
                        <input type="text" name="product" id="product" value ="{% if product %}{{product}}{% endif %}">
                        {% if error == 'Product not found' %}
                        <div class="error-mesg">{{ error }}</div>
                        {% endif %}
                    </div>
                </div>
                <div class="input-group">
                    <label>Quantity</label>
                    <div class="input-field {% if error == 'Not enough quantity' %}error-field{% endif %}">
                        <input type="number" name="quantity" id="quantity" value ="{% if quantity %}{{quantity}}{% endif %}" required>
                        {% if error == 'Not enough quantity' %}
                        <div class="error-mesg">{{ error }}</div>
                        {% endif %}
                    </div>
                </div>
                <div class="input-group">
                    <label>Customer</label>
                    <div class="input-field">
                        <input type="text" name="customer" id="customer" value="{% if customer %}{{customer}}{% endif %}" required>
                    </div>
                </div>
                <div class="input-group">
                    <label>Customer email</label>
                    <div class="input-field">
                        <input type="email" name="customer_email" id="customer_email" value="{% if customer_email %}{{customer_email}}{% endif %}" required>
                    </div>
                </div>
                <div class="input-group">
                    <label>Customer phone</label>
                    <div class="input-field">
                        <input type="tel" name="customer_phone" id="customer_phone" value="{%if customer_phone %}{{customer_phone}}{% endif %}">
                    </div>
                </div>
                <div class="input-group">
                    <label>User</label>
                    <div class="input-field">
                        <input type="text" name="user" id="user" value="{% if user %}{{user}}{% endif %}" required>
                    </div>
                </div>
                <div class="input-filed">
                    <input type="submit" value="Add" name="add" id="add">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/sales/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="content">
        <div class='search'>
            <form action="{{ url_for('sales.search_sale', search='') }}" method="get">
                <input type='text' placeholder='Search' name='search' id='search'>
                <input type='submit' value="Search">
            </form>
        </div>
        <!--navigation through the records-->
        <div class="view">
            <h1 style="text-align: center;">Sales information</h1>
            {% if sales|length < 1 %}
            <h4  style="text-align: center;"> There are no sale, create one below!</h4>
            {% else %}
            <table>
                <tr>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Customer name</th>
                    <th>Customer email</th>
                    <th>Customer phone</th>
                    <th>User</th>
                    <th>Date</th>
                    <th>Id</th>
                </tr>
                {% for sale in sales %}
                    <tr>
                        <td>{{ sale.product_name }}</td>
                        <td>{{ sale.product_quantity }}</td>
                        <td>{{ sale.customer_name }}</td>
                        <td>{{ sale.customer_email }}</td>
                        <td>{{ sale.customer_phone }}</td>
                        <td>{{ sale.user_name }}</td>
                        <td>{{ sale.date.date() }}</td>
                        <td><a href="/sales/info_sale/{{ sale.id }}">{{ sale.id }}</a></td>
                    </tr>
                {% endfor %}
            </table>
            {% endif %}
        </div>
        <body>
            <div class="add">
                {% if current_user.has_role('admin') or current_user.has_role('editor')%}
                <a href="{{ url_for('sales.add_sale', search='') }}">Add Sale</a>
                <div class="download-container">
                    <button id="downloadBtn">Download</button>
                    <div id="dropdown" class="dropdown-content">
                        <a href="#" class="download-link" data-table="sales" data-format="json">JSON</a>
                        <a href="#" class="download-link" data-table="sales" data-format="csv">CSV</a>
                    </div>
                </div>
                <div class="upload-container">
                    <button id="openModalBtn">Upload</button>
                    <div id="uploadModal" class="modal">
                        <div class="modal-content">
                            <span class="close">&times;</span>
                            <form id="uploadForm">
                                <input type="file" id="fileInput" name="file">
                                <button type="submit">Upload</button>
                            </form>
                        </div>
                    </div>
                </div>
                {% endif %}
                <div id="popup" class="popup"></div>
            </div>
        </body>
    </div>
    {% endblock %}

app/templates/sales/info_sale.html
{% extends 'base.html' %}

{% block head %}
<title>CRM</title>
{% endblock %}

<div class="content">
{% block content %}
<div class="content">
    <div class="info">
        <div class="table_box">
            <table>
                <tr>
                    <th>Product</th>
                    <td>{{ sale.product_name }}</td>
                </tr>
                <tr>
                    <th>Quantity</th>
                    <td>{{ sale.product_quantity }}</td>
                </tr>
                <tr>
                    <th>Customer name</th>
                    <td>{{ sale.customer_name }}</td>
                </tr>
                <tr>
                    <th>Customer email</th>
                    <td>{{ sale.customer_email }}</td>
                </tr>
                <tr>
                    <th>Customer phone</th>
                    <td>{{ sale.customer_phone }}</td>
                </tr>
                <tr>
                    <th>User</th>
                    <td>{{ sale.user_name }}</td>
                </tr>
                <tr>
                    <th>Date</th>
                    <td>{{ sale.date.date() }}</td>
                </tr>
            </table>
        </div>
        <div class="edit">
            {% if current_user.has_role('admin') or current_user.has_role('editor')%}
            <a href="/sales/update_sale/{{sale.id}}" id="update">Update</a>
            <br>
            <a href="{{ url_for('sales.delete_sale', id=sale.id) }}" onclick="return confirm('are you sure you want delete this record?!')" id="delete">Delete</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/sales/search_sale.html
{% extends 'base.html' %}

{% block head %}
<title>CRM</title>
{% endblock %}

{% block content %}
<div class="content">
    <div class='search'>
        <form action="{{ url_for('sales.search_sale', search='') }}" method="get">
            <input type='text' placeholder='Search' name='search' id='search'>
            <input type='submit' value="Search">
        </form>
    </div>
    <!--navigation through the records-->
    <div class="view">
        <h1 style="text-align: center;">Sales information</h1>
        {% if sales|length < 1 %}
        <h4  style="text-align: center;"> No search results</h4>
        {% else %}
        <table>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Customer name</th>
                <th>Customer email</th>
                <th>Customer phone</th>
                <th>User</th>
                <th>Date</th>
                <th>Id</th>
            </tr>
            {% for sale in sales %}
                <tr>
                    <td>{{ sale.product_name }}</td>
                    <td>{{ sale.product_quantity }}</td>
                    <td>{{ sale.customer_name }}</td>
                    <td>{{ sale.customer_email }}</td>
                    <td>{{ sale.customer_phone }}</td>
                    <td>{{ sale.user_name }}</td>
                    <td>{{ sale.date.date() }}</td>
                    <td><a href="/sales/info_sale/{{ sale.id }}">{{ sale.id }}</a></td>
                </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/sales/update_sale.html
{% extends 'base.html' %}

{% block head %}
<title>CRM</title>
{% endblock %}

{% block content %}
<div class="content">
    <div class="add_update">
        <div class="form-box">
            <h1  style="text-align: center;">Update sale information</h1>
            <form action="/sales/update_sale/{{sale.id}}" method="post">
                <div class="input-group">
                    <label>Product</label>
                    <div class="input-field {% if error == 'Product not found' %}error-field{% endif %}">
                        <input type="text" name="product" id="product" value="{{ sale.product_name }}" required>
                        {% if error == 'product not found' %}
                        <div class="error-mesg">{{ error }}</div>
                        {% endif %}
                    </div>
                </div>
                <div class="input-group">
                    <label>Quantity</label>
                    <div class="input-field {% if error == 'Not enough quantity' %}error-field{% endif %}">
                        <input type="number" name="quantity" id="quantity" value="{{ sale.product_quantity }}" required>
                        {% if error == 'Not enough quantity' %}
                        <div class="error-mesg">{{ error }}</div>
                        {% endif %}
                    </div>
                </div>
                <div class="input-group">
                    <label>Customer</label>
                    <div class="input-field">
                        <input type="text" name="customer" id="customer" value="{{ sale.customer_name }}" required>
                    </div>
                </div>
                <div class="input-group">
                    <label>Customer email</label>
                    <div class="input-field">
                        <input type="email" name="customer_email" id="customer" value="{{ sale.customer_email }}" required>
                    </div>
                </div>
                <div class="input-group">
                    <label>Customer phone</label>
                    <div class="input-field">
                        <input type="tel" name="customer_phone" value="{{ sale.customer_phone }}" id="customer">
                    </div>
                </div>
                <div class="input-group">
                    <label>user</label>
                    <div class="input-field">
                        <input type="text" name="user" id="user" value="{{ sale.user_name }}" required>
                    </div>
                </div>   
                <div class="input-field">
                    {% if current_user.has_role('admin') or current_user.has_role('editor')%}
                    <input type="submit" value="Update" name="add" id="add">
                    {% endif %}
                </div> 
            </form>  
        </div>
    </div>
</div>
{% endblock %}